name: baket_mobile
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  either_dart: ^1.0.0
  envied: ^0.5.3
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.10+1
  google_fonts: ^6.2.1
  logger: ^2.4.0
  flutter_native_splash: ^2.4.3
  provider: ^6.1.2
  pbp_django_auth: ^0.4.0
  image_picker: ^1.0.7
  http: ^1.1.0
  intl: ^0.17.0
  lucide_icons: ^0.257.0
  get: ^4.6.6
  super_tooltip: ^2.0.9
  extended_nested_scroll_view: ^6.2.1
  infinite_scroll_pagination: ^4.1.0
  flutter_rating_stars: ^1.1.0
  cached_network_image: ^3.4.1

dev_dependencies:
  build_runner: ^2.4.8
  envied_generator: ^0.5.3
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
  very_good_analysis: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/svgs/
